
services:
  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=nutrition_app
      - DOMAIN=${DOMAIN:-http://localhost:3000}
      - SMTP_HOST=${SMTP_HOST:-smtp.cesky-hosting.cz}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURITY=${SMTP_SECURITY:-tls}
      - SMTP_USER=${SMTP_USER:-noreply@jrycho.cz}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-noreply@jrycho.cz}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Jrycho}
      - SMTP_PASS=${SMTP_PASS}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - OFF_API_BASE_URL=${OFF_API_BASE_URL:-https://world.openfoodfacts.org}

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
volumes:
  mongo_data:
