services:
  web:
    image: jrycho/diplomka-web:latest
    pull_policy: always
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:?NEXT_PUBLIC_API_URL is required}
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:?NEXT_PUBLIC_API_BASE is required}
      NEXT_PUBLIC_OFF_API_BASE_URL: ${NEXT_PUBLIC_OFF_API_BASE_URL:-https://world.openfoodfacts.org}
    depends_on:
      - fastapi
    restart: unless-stopped

  fastapi:
    image: jrycho/diplomka-fastapi:latest
    pull_policy: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI:?MONGO_URI is required}
      MONGO_DB_NAME: ${MONGO_DB_NAME:?MONGO_DB_NAME is required}
      RESEND_API_KEY: ${RESEND_API_KEY:?RESEND_API_KEY is required}
      DOMAIN: ${DOMAIN:?DOMAIN is required}
      SECRET_KEY: ${SECRET_KEY:?SECRET_KEY is required}
      SMTP_PASS: ${SMTP_PASS:?SMTP_PASS is required}
      CORS_ORIGINS: ${CORS_ORIGINS:-https://jrycho.cz,https://www.jrycho.cz}
      OFF_API_BASE_URL: ${OFF_API_BASE_URL:-https://world.openfoodfacts.org}
    restart: unless-stopped
