import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Nomingomi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* site-wide background + text come from your CSS variables via Tailwind tokens */}
      <body className="min-h-screen bg-background-yellow-500 text-foreground antialiased">
        <Navbar />
        {/* spacer only needed if Navbar is fixed */}
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
